name: Teardown Linux

description: Stuff that should always run at the end of a linux job

runs:
  using: composite
  steps:
    - name: Hold runner for 2 hours or until ssh sessions have drained
      # TODO working-directory: !{{ pytorch_directory }}
      # Always hold for active ssh sessions
      shell: bash
      run: .github/scripts/wait_for_ssh_to_drain.sh

    - name: Kill containers, clean up images
      shell: bash
      run: |
        # ignore expansion of "docker ps -q" since it could be empty
        # shellcheck disable=SC2046
        docker stop $(docker ps -q) || true
        # Prune all of the docker images
        docker system prune -af
